# https://github.com/marketplace/actions/deploy-to-github-pages

name: Build and Deploy

on:
  push:
    tags:
      - "v*"

# on:
#   push:
#     branches:
#       - workspaces

permissions:
  contents: write

jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3

      - uses: extractions/setup-just@v1

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - uses: actions-rs/install@v0.1
        with:
          crate: cargo-audit
          version: latest
          use-tool-cache: true


      - name: Install sd ğŸ”§ # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          cargo install sd

      - name: Install and Build ğŸ”§ # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          cd packages/metapage-app
          just deploy-tag-version
        env:
          DOCKER_REGISTRY: ghcr.io
          # https://docs.github.com/en/free-pro-team@latest/actions/reference/authentication-in-a-workflow#about-the-github_token-secret
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}



      # - name: Install and Build ğŸ”§ # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
      #   run: |
      #     cd packages/metapage-app
      #     just browser/build
      #     # npm ci
      #     # npm run build

      # - name: Deploy ğŸš€
      #   uses: JamesIves/github-pages-deploy-action@v4
      #   with:
      #     folder: browser/dist # The folder the action should deploy.
      #     target-folder: docs
